name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    # Build matrix for macOS 15.5 ARM
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        # macOS builds (arm64, macOS 15.5)
        - { name: macOS 15.5 ARM, os: macos-15 }
        config:
        - { name: Shared, flags: -DBUILD_SHARED_LIBS=TRUE }
        - { name: Static, flags: -DBUILD_SHARED_LIBS=FALSE }

    steps:
    # Install SFML on macOS using Homebrew
    - name: Install SFML (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install sfml

    # Checkout code
    - name: Checkout
      uses: actions/checkout@v4

    # Configure CMake for the current platform and configuration
    - name: Configure
      run: cmake -B build ${{ matrix.platform.flags }} ${{ matrix.config.flags }}
      env:
        SFML_DIR: ${{ env.SFML_DIR }}

    # Build the project
    - name: Build
      run: cmake --build build --config Release